import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import faviconImg from "@/public/images/favicon.ico"

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Hulu 2.0",
  
//   //description: "Generated by create next app",
// };

export default function StandardLayout({children}) {
  return (
    <html>
      <head>
        <title>VidVerse</title>
        <link rel="icon" href={faviconImg.src} type="image/x-icon"/>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
    
  );
}
